const inventory={
 'ford-f150':{year:2022,make:'Ford',model:'F-150 XLT',type:'Truck',price:32900,miles:46200,color:'Silver'},
 'ford-transit':{year:2021,make:'Ford',model:'Transit 250 Cargo',type:'Van',price:28900,miles:61800,color:'White'},
 'mercedes-sprinter':{year:2020,make:'Mercedes-Benz',model:'Sprinter Passenger',type:'Van',price:38900,miles:73300,color:'Gray'},
 'honda-civic':{year:2022,make:'Honda',model:'Civic Sedan',type:'Sedan',price:21900,miles:35300,color:'White'},
 'lexus-es350':{year:2021,make:'Lexus',model:'ES 350',type:'Sedan',price:29900,miles:49500,color:'Black'},
 'bmw-330i':{year:2020,make:'BMW',model:'330i Sedan',type:'Sedan',price:26900,miles:57400,color:'Blue',sold:true}
};
const key=document.body.dataset.vehicle,car=inventory[key],$=id=>document.getElementById(id);
const names=['front','side','rear','dashboard','front-seats','rear-cabin'];
const words={
 en:{demo:'PRIVATE WEBSITE CONCEPT · VEHICLES, PHOTOS, PRICES AND SPECS ARE FICTIONAL EXAMPLES',inventory:'Inventory',back:'Back to inventory',sample:'SAMPLE VEHICLE',sold:'SOLD EXAMPLE',mileage:'Mileage',body:'Body',color:'Color',year:'Year',finTitle:'Need financing? Let’s talk.',finText:'Ask the dealership about financing options for this vehicle.',finNote:'Preview copy · financing services and terms must be confirmed by JKK Auto Group.',inquiry:'Ask about this vehicle',inquiryNote:'This is a demonstration. No inquiry is sent. Real vehicle photos and verified details would replace these illustrations.',expand:'Enlarge photo',close:'Close enlarged photo',previous:'Previous photo',next:'Next photo',prepared:'Sample site prepared by',photo:['Front view','Side view','Rear view','Dashboard','Front seats','Rear seats / cargo area'],types:{Truck:'Truck',Van:'Van',Sedan:'Sedan'},colors:{Silver:'Silver',White:'White',Gray:'Gray',Black:'Black',Blue:'Blue'}},
 es:{demo:'CONCEPTO DE SITIO WEB · VEHÍCULOS, FOTOS, PRECIOS Y DATOS SON EJEMPLOS FICTICIOS',inventory:'Inventario',back:'Volver al inventario',sample:'VEHÍCULO DE MUESTRA',sold:'EJEMPLO VENDIDO',mileage:'Millaje',body:'Tipo',color:'Color',year:'Año',finTitle:'¿Necesitas financiamiento? Hablemos.',finText:'Consulta al concesionario por opciones de financiamiento para este vehículo.',finNote:'Texto de muestra · JKK Auto Group debe confirmar el servicio y los términos.',inquiry:'Preguntar por este vehículo',inquiryNote:'Esta es una demostración. No se envían consultas. Estas ilustraciones se reemplazarían por fotos reales y datos verificados.',expand:'Ampliar foto',close:'Cerrar foto ampliada',previous:'Foto anterior',next:'Foto siguiente',prepared:'Sitio de muestra preparado por',photo:['Vista frontal','Vista lateral','Vista trasera','Tablero','Asientos delanteros','Asientos traseros / área de carga'],types:{Truck:'Camioneta',Van:'Van',Sedan:'Sedán'},colors:{Silver:'Plateado',White:'Blanco',Gray:'Gris',Black:'Negro',Blue:'Azul'}}
};
let lang=new URLSearchParams(location.search).get('lang')==='es'?'es':'en',selected=0;
const path=i=>`../assets/vehicles/${key}-${names[i]}.webp`,label=i=>`${car.year} ${car.make} ${car.model} — ${words[lang].photo[i]}`;
function renderPhoto(){const img=$('photo');img.src=path(selected);img.alt=label(selected);$('caption').textContent=`${selected+1} / 6 · ${words[lang].photo[selected]}`;document.querySelectorAll('.thumb').forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===selected));b.setAttribute('aria-label',`${words[lang].photo[i]} (${i+1}/6)`);b.querySelector('img').alt=label(i)});$('bigPhoto').src=path(selected);$('bigPhoto').alt=label(selected);$('lightLabel').textContent=`${selected+1} / 6 · ${words[lang].photo[selected]}`}
function render(){const w=words[lang],title=`${car.year} ${car.make} ${car.model}`,home=`../${lang==='es'?'?lang=es':''}#inventory`;document.documentElement.lang=lang;document.title=`${title} | JKK Auto Group`;document.querySelector('meta[name=description]').content=lang==='es'?`Galería de muestra: ${title}. Seis fotos ilustrativas.`:`Sample gallery: ${title}. Six illustrative photos.`;$('demo').textContent=w.demo;$('navInventory').textContent=w.inventory;$('navInventory').href=home;$('crumbInventory').textContent=w.inventory;$('crumbInventory').href=home;$('back').textContent=`← ${w.back}`;$('back').href=home;$('brand').href=home;$('langToggle').textContent=lang==='es'?'ENGLISH':'ESPAÑOL';$('langToggle').setAttribute('aria-label',lang==='es'?'View in English':'Ver en español');$('sample').textContent=car.sold?w.sold:w.sample;$('title').textContent=title;$('crumbCar').textContent=title;$('price').textContent=car.sold?w.sold:'$'+car.price.toLocaleString('en-US');$('price').classList.toggle('sold',!!car.sold);$('specs').innerHTML=[[w.year,car.year],[w.mileage,car.miles.toLocaleString(lang==='es'?'es-US':'en-US')+(lang==='es'?' millas':' mi')],[w.body,w.types[car.type]],[w.color,w.colors[car.color]]].map(([a,b])=>`<div class="spec"><small>${a}</small><strong>${b}</strong></div>`).join('');$('finTitle').textContent=w.finTitle;$('finText').textContent=w.finText;$('finNote').textContent=w.finNote;$('inquiry').textContent=w.inquiry;$('inquiry').href=home.replace('#inventory','#contact');$('inquiryNote').textContent=w.inquiryNote;$('expand').textContent=w.expand;$('mainPhoto').setAttribute('aria-label',w.expand);$('closeLight').setAttribute('aria-label',w.close);$('prev').setAttribute('aria-label',w.previous);$('next').setAttribute('aria-label',w.next);$('prepared').textContent=w.prepared;renderPhoto()}
$('thumbs').innerHTML=names.map((_,i)=>`<button class="thumb" type="button" data-index="${i}"><img src="${path(i)}" loading="lazy" alt=""></button>`).join('');$('thumbs').addEventListener('click',e=>{const b=e.target.closest('button[data-index]');if(!b)return;selected=Number(b.dataset.index);renderPhoto()});$('mainPhoto').addEventListener('click',()=>{$('lightbox').showModal();renderPhoto()});$('closeLight').addEventListener('click',()=>$('lightbox').close());$('lightbox').addEventListener('click',e=>{if(e.target===$('lightbox'))$('lightbox').close()});function shift(n){selected=(selected+n+6)%6;renderPhoto()}$('prev').addEventListener('click',()=>shift(-1));$('next').addEventListener('click',()=>shift(1));document.addEventListener('keydown',e=>{if(!$('lightbox').open)return;if(e.key==='ArrowLeft')shift(-1);if(e.key==='ArrowRight')shift(1)});$('langToggle').addEventListener('click',()=>{lang=lang==='en'?'es':'en';history.replaceState(null,'',location.pathname+(lang==='es'?'?lang=es':''));render()});render();
